name: ansque
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^3.1.0
  intl: ^0.17.0
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  country_code_picker: ^2.0.2
  flutter_svg: ^1.0.3
  flutter_hi_icons:
    git:
      url: https://github.com/stevenosse/flutter_hi_icons
  iconsax: ^0.0.8
  dotted_border: ^2.0.0+2
  firebase_auth: ^3.3.17
  flash: ^2.0.3+2
  ionicons: ^0.1.2
  firebase_core: ^1.17.0
  objectbox: ^1.5.0
  file_picker: ^4.5.1
  open_file: ^3.2.1
  cloud_firestore: ^3.1.16


dev_dependencies:
  flutter_test:
    sdk: flutter

  fast_i18n: ^5.12.3
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/illustrations/
    - assets/images/


  fonts:
    - family: Century Gothic
      fonts:
        - asset: assets/fonts/century_gothic/Century_Gothic.ttf
        - asset: assets/fonts/century_gothic/CenturyGothic.ttf
        - asset: assets/fonts/century_gothic/GOTHICB.TTF
          weight: 700
        - asset: assets/fonts/century_gothic/GOTHICB0.TTF
          weight: 900
        - asset: assets/fonts/century_gothic/GOTHICBI.TTF
          weight: 900
          style: italic
        - asset: assets/fonts/century_gothic/GOTHICI.TTF
          style: italic